require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PresidentesController do

  # This should return the minimal set of attributes required to create a valid
  # Presidente. As you add validations to Presidente, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PresidentesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all presidentes as @presidentes" do
      presidente = Presidente.create! valid_attributes
      get :index, {}, valid_session
      assigns(:presidentes).should eq([presidente])
    end
  end

  describe "GET show" do
    it "assigns the requested presidente as @presidente" do
      presidente = Presidente.create! valid_attributes
      get :show, {:id => presidente.to_param}, valid_session
      assigns(:presidente).should eq(presidente)
    end
  end

  describe "GET new" do
    it "assigns a new presidente as @presidente" do
      get :new, {}, valid_session
      assigns(:presidente).should be_a_new(Presidente)
    end
  end

  describe "GET edit" do
    it "assigns the requested presidente as @presidente" do
      presidente = Presidente.create! valid_attributes
      get :edit, {:id => presidente.to_param}, valid_session
      assigns(:presidente).should eq(presidente)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Presidente" do
        expect {
          post :create, {:presidente => valid_attributes}, valid_session
        }.to change(Presidente, :count).by(1)
      end

      it "assigns a newly created presidente as @presidente" do
        post :create, {:presidente => valid_attributes}, valid_session
        assigns(:presidente).should be_a(Presidente)
        assigns(:presidente).should be_persisted
      end

      it "redirects to the created presidente" do
        post :create, {:presidente => valid_attributes}, valid_session
        response.should redirect_to(Presidente.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved presidente as @presidente" do
        # Trigger the behavior that occurs when invalid params are submitted
        Presidente.any_instance.stub(:save).and_return(false)
        post :create, {:presidente => {}}, valid_session
        assigns(:presidente).should be_a_new(Presidente)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Presidente.any_instance.stub(:save).and_return(false)
        post :create, {:presidente => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested presidente" do
        presidente = Presidente.create! valid_attributes
        # Assuming there are no other presidentes in the database, this
        # specifies that the Presidente created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Presidente.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => presidente.to_param, :presidente => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested presidente as @presidente" do
        presidente = Presidente.create! valid_attributes
        put :update, {:id => presidente.to_param, :presidente => valid_attributes}, valid_session
        assigns(:presidente).should eq(presidente)
      end

      it "redirects to the presidente" do
        presidente = Presidente.create! valid_attributes
        put :update, {:id => presidente.to_param, :presidente => valid_attributes}, valid_session
        response.should redirect_to(presidente)
      end
    end

    describe "with invalid params" do
      it "assigns the presidente as @presidente" do
        presidente = Presidente.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Presidente.any_instance.stub(:save).and_return(false)
        put :update, {:id => presidente.to_param, :presidente => {}}, valid_session
        assigns(:presidente).should eq(presidente)
      end

      it "re-renders the 'edit' template" do
        presidente = Presidente.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Presidente.any_instance.stub(:save).and_return(false)
        put :update, {:id => presidente.to_param, :presidente => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested presidente" do
      presidente = Presidente.create! valid_attributes
      expect {
        delete :destroy, {:id => presidente.to_param}, valid_session
      }.to change(Presidente, :count).by(-1)
    end

    it "redirects to the presidentes list" do
      presidente = Presidente.create! valid_attributes
      delete :destroy, {:id => presidente.to_param}, valid_session
      response.should redirect_to(presidentes_url)
    end
  end

end
